[package]
name = "varta-client"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Varta agent API — emits VLP frames over a Unix Domain Socket."
authors = ["Alexander Ramirez"]
repository = "https://github.com/aramirez087/Varta"

[features]
default = []
panic-handler = []

[dependencies]

[dependencies.varta-vlp]
path = "../varta-vlp"

[[example]]
name = "basic"

[[example]]
name = "with_payload"

[[example]]
name = "with_panic_handler"
required-features = ["panic-handler"]
