//! Conformance vector contract.
//!
//! Loads `tools/vlp-test-vectors.json` and asserts every entry round-trips
//! through the Rust reference implementation. Any wire-format drift fails
//! this test before reaching CI; external implementers run the same JSON
//! file against their own decoders to certify conformance.
//!
//! The JSON file is regenerated by:
//!
//! ```sh
//! cargo run -p varta-vlp --example gen_test_vectors --features "std crypto"
//! ```
//!
//! See `book/src/spec/conformance.md` for the schema and the cross-language
//! recipe.

use varta_vlp::{crc32c, DecodeError, Frame, Status};

const VECTORS: &str = include_str!("../../../tools/vlp-test-vectors.json");

// ---------------------------------------------------------------------------
// Minimal JSON-subset parser.
//
// Scoped to the exact shape of `vlp-test-vectors.json`. Handles: objects,
// arrays, double-quoted strings (with `\"`, `\\`, `\n` escapes), integers,
// `null`, `true`, `false`. Does not handle floats, unicode escapes, or
// scientific notation — none of which appear in our schema.
// ---------------------------------------------------------------------------

/// Extract every top-level element of `array_key` as an opaque JSON slice
/// (without the surrounding `[` / `]`).
fn array_elements<'a>(src: &'a str, array_key: &str) -> Vec<&'a str> {
    let body = locate_value(src, array_key).expect("array key");
    assert!(body.starts_with('['), "{array_key} is not an array");
    let inner = &body[1..body.len() - 1];
    split_top_level(inner)
}

/// Locate the raw JSON value associated with `key` inside `obj`. Walks the
/// object's properties at depth 0 so a `key` substring buried inside a string
/// VALUE (description text, hex blob) does not produce a false match.
///
/// `obj` may include the outer `{` `}` or may be already trimmed to the body.
fn locate_value<'a>(obj: &'a str, key: &str) -> Option<&'a str> {
    let body = obj.trim().trim_start_matches('{').trim_end_matches('}');
    let bytes = body.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        while i < bytes.len() && (bytes[i].is_ascii_whitespace() || bytes[i] == b',') {
            i += 1;
        }
        if i >= bytes.len() {
            break;
        }
        if bytes[i] != b'"' {
            // Malformed or end-of-object.
            return None;
        }
        let key_start = i + 1;
        let key_end_plus_one = skip_string(body, i);
        let key_str = &body[key_start..key_end_plus_one - 1];
        i = key_end_plus_one;
        while i < bytes.len() && (bytes[i].is_ascii_whitespace() || bytes[i] == b':') {
            i += 1;
        }
        if i >= bytes.len() {
            return None;
        }
        let value_end = end_of_value(body, i);
        if key_str == key {
            return Some(&body[i..value_end]);
        }
        i = value_end;
    }
    None
}

fn skip_string(src: &str, start: usize) -> usize {
    let bytes = src.as_bytes();
    debug_assert_eq!(bytes[start], b'"');
    let mut i = start + 1;
    while i < bytes.len() {
        if bytes[i] == b'\\' {
            i += 2;
            continue;
        }
        if bytes[i] == b'"' {
            return i + 1;
        }
        i += 1;
    }
    bytes.len()
}

fn end_of_value(src: &str, start: usize) -> usize {
    let bytes = src.as_bytes();
    match bytes[start] {
        b'"' => skip_string(src, start),
        b'{' | b'[' => {
            let open = bytes[start];
            let close = if open == b'{' { b'}' } else { b']' };
            let mut depth = 1;
            let mut i = start + 1;
            while i < bytes.len() && depth > 0 {
                match bytes[i] {
                    b'"' => {
                        i = skip_string(src, i);
                        continue;
                    }
                    b if b == open => depth += 1,
                    b if b == close => depth -= 1,
                    _ => {}
                }
                i += 1;
            }
            i
        }
        _ => {
            // Number, null, true, false. Read until terminator.
            let mut i = start;
            while i < bytes.len() {
                let b = bytes[i];
                if b == b',' || b == b'}' || b == b']' || b.is_ascii_whitespace() {
                    break;
                }
                i += 1;
            }
            i
        }
    }
}

fn split_top_level(inner: &str) -> Vec<&str> {
    let bytes = inner.as_bytes();
    let mut out = Vec::new();
    let mut depth: i32 = 0;
    let mut start = 0;
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'"' => {
                i = skip_string(inner, i);
                continue;
            }
            b'{' | b'[' => depth += 1,
            b'}' | b']' => depth -= 1,
            b',' if depth == 0 => {
                out.push(inner[start..i].trim());
                start = i + 1;
            }
            _ => {}
        }
        i += 1;
    }
    let tail = inner[start..].trim();
    if !tail.is_empty() {
        out.push(tail);
    }
    out
}

fn read_string(obj: &str, key: &str) -> String {
    let raw = locate_value(obj, key).unwrap_or_else(|| panic!("missing key: {key}"));
    assert!(
        raw.starts_with('"') && raw.ends_with('"'),
        "{key} is not a string: {raw}"
    );
    let inner = &raw[1..raw.len() - 1];
    let mut out = String::with_capacity(inner.len());
    let mut bytes = inner.bytes();
    while let Some(b) = bytes.next() {
        if b == b'\\' {
            match bytes.next() {
                Some(b'"') => out.push('"'),
                Some(b'\\') => out.push('\\'),
                Some(b'n') => out.push('\n'),
                Some(other) => panic!("unhandled escape: \\{}", other as char),
                None => break,
            }
        } else {
            out.push(b as char);
        }
    }
    out
}

fn read_u64(obj: &str, key: &str) -> u64 {
    let raw = locate_value(obj, key).unwrap_or_else(|| panic!("missing key: {key}"));
    raw.parse::<u64>().expect("integer")
}

fn read_u32(obj: &str, key: &str) -> u32 {
    let raw = locate_value(obj, key).unwrap_or_else(|| panic!("missing key: {key}"));
    raw.parse::<u32>().expect("u32")
}

fn read_nullable_string(obj: &str, key: &str) -> Option<String> {
    let raw = locate_value(obj, key).unwrap_or_else(|| panic!("missing key: {key}"));
    if raw == "null" {
        None
    } else {
        assert!(raw.starts_with('"') && raw.ends_with('"'));
        Some(raw[1..raw.len() - 1].to_string())
    }
}

fn decode_hex(s: &str) -> Vec<u8> {
    assert!(s.len() % 2 == 0, "odd hex length: {s}");
    (0..s.len() / 2)
        .map(|i| u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).expect("hex"))
        .collect()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn every_crc_vector_matches() {
    let mut count = 0;
    for entry in array_elements(VECTORS, "crc32c_vectors") {
        let id = read_string(entry, "id");
        let input = decode_hex(&read_string(entry, "input_hex"));
        let expected = decode_hex(&read_string(entry, "expected_crc_hex"));
        let computed = crc32c::compute(&input);
        let expected_u32 = u32::from_be_bytes([expected[0], expected[1], expected[2], expected[3]]);
        assert_eq!(
            computed, expected_u32,
            "CRC mismatch for {id}: got {computed:#010x}, expected {expected_u32:#010x}"
        );
        count += 1;
    }
    assert!(count >= 5, "expected at least 5 CRC vectors, got {count}");
}

#[test]
fn every_frame_vector_round_trips_or_errors() {
    let mut success = 0;
    let mut error = 0;
    for entry in array_elements(VECTORS, "frame_vectors") {
        let id = read_string(entry, "id");
        let kind = read_string(entry, "kind");
        match kind.as_str() {
            "encode_decode_roundtrip" => {
                let expected_hex = read_string(entry, "expected_wire_hex");
                let expected_bytes = decode_hex(&expected_hex);
                assert_eq!(expected_bytes.len(), 32, "{id}: wire must be 32 B");

                let inputs_raw = locate_value(entry, "inputs").expect("inputs");
                let inputs = inputs_raw.trim_start_matches('{').trim_end_matches('}');
                let status = match read_string(inputs, "status").as_str() {
                    "ok" => Status::Ok,
                    "degraded" => Status::Degraded,
                    "critical" => Status::Critical,
                    "stall" => Status::Stall,
                    other => panic!("unknown status name: {other}"),
                };
                let pid = read_u32(inputs, "pid");
                let timestamp = read_u64(inputs, "timestamp");
                let nonce = read_u64(inputs, "nonce");
                let payload = read_u32(inputs, "payload");

                let frame = Frame::new(status, pid, timestamp, nonce, payload);
                let mut buf = [0u8; 32];
                frame.encode(&mut buf);
                assert_eq!(
                    &buf[..],
                    &expected_bytes[..],
                    "{id}: encoded bytes differ from golden"
                );

                // Round-trip the golden bytes through decode and check fields.
                let mut as_array = [0u8; 32];
                as_array.copy_from_slice(&expected_bytes);
                let decoded = Frame::decode(&as_array).expect("golden must decode");
                assert_eq!(decoded.status, status);
                assert_eq!(decoded.pid, pid);
                assert_eq!(decoded.timestamp, timestamp);
                assert_eq!(decoded.nonce, nonce);
                assert_eq!(decoded.payload, payload);
                success += 1;
            }
            "decode_error" => {
                let expected_error =
                    read_nullable_string(entry, "expected_decode_error").expect("error name");
                let wire = decode_hex(&read_string(entry, "wire_hex"));
                assert_eq!(wire.len(), 32, "{id}: wire must be 32 B");
                let mut as_array = [0u8; 32];
                as_array.copy_from_slice(&wire);

                let err = Frame::decode(&as_array)
                    .err()
                    .unwrap_or_else(|| panic!("{id}: expected decode error, got Ok"));
                let actual = error_variant(&err);
                assert_eq!(
                    actual, expected_error,
                    "{id}: expected {expected_error}, got {actual} ({err:?})"
                );
                error += 1;
            }
            other => panic!("{id}: unknown frame_vector kind: {other}"),
        }
    }
    assert!(success >= 6, "expected ≥6 encode/decode goldens, got {success}");
    assert!(error >= 8, "expected ≥8 decode-error goldens, got {error}");
}

fn error_variant(err: &DecodeError) -> &'static str {
    match err {
        DecodeError::BadMagic => "BadMagic",
        DecodeError::BadVersion => "BadVersion",
        DecodeError::BadCrc { .. } => "BadCrc",
        DecodeError::BadStatus(_) => "BadStatus",
        DecodeError::StallOnWire => "StallOnWire",
        DecodeError::BadPid(_) => "BadPid",
        DecodeError::BadTimestamp(_) => "BadTimestamp",
        DecodeError::BadNonce { .. } => "BadNonce",
    }
}

#[cfg(feature = "crypto")]
#[test]
fn every_secure_frame_vector_round_trips() {
    use varta_vlp::crypto::{kdf, open, seal, Key};

    let mut count = 0;
    for entry in array_elements(VECTORS, "secure_frame_vectors") {
        let id = read_string(entry, "id");
        let kind = read_string(entry, "kind");
        match kind.as_str() {
            "shared_key_seal" => {
                let key_bytes = decode_hex(&read_string(entry, "key_hex"));
                let iv_random = decode_hex(&read_string(entry, "iv_random_hex"));
                let iv_counter = read_u32(entry, "iv_counter");
                let plaintext_vec = decode_hex(&read_string(entry, "plaintext_hex"));
                let expected = decode_hex(&read_string(entry, "expected_wire_hex"));

                let mut key_array = [0u8; 32];
                key_array.copy_from_slice(&key_bytes);
                let key = Key::from_bytes(key_array);

                let mut plaintext = [0u8; 32];
                plaintext.copy_from_slice(&plaintext_vec);

                let mut nonce = [0u8; 12];
                nonce[..8].copy_from_slice(&iv_random);
                nonce[8..].copy_from_slice(&iv_counter.to_le_bytes());
                let (ct, tag) = seal(key.as_bytes(), &nonce, b"", &plaintext).expect("seal");

                let mut wire = Vec::with_capacity(60);
                wire.extend_from_slice(&iv_random);
                wire.extend_from_slice(&iv_counter.to_le_bytes());
                wire.extend_from_slice(&ct);
                wire.extend_from_slice(&tag);
                assert_eq!(wire, expected, "{id}: shared-key wire mismatch");

                let recovered = open(key.as_bytes(), &nonce, b"", &ct, &tag).expect("open");
                assert_eq!(recovered.as_slice(), plaintext.as_slice());
                count += 1;
            }
            "master_key_seal" => {
                let master_bytes = decode_hex(&read_string(entry, "master_key_hex"));
                let agent_pid = read_u32(entry, "agent_pid");
                let iv_random = decode_hex(&read_string(entry, "iv_random_hex"));
                let iv_counter = read_u32(entry, "iv_counter");
                let plaintext_vec = decode_hex(&read_string(entry, "plaintext_hex"));
                let expected_agent_key = decode_hex(&read_string(entry, "derived_agent_key_hex"));
                let expected = decode_hex(&read_string(entry, "expected_wire_hex"));

                let mut master_array = [0u8; 32];
                master_array.copy_from_slice(&master_bytes);
                let master = Key::from_bytes(master_array);
                let agent_key = kdf::derive_agent_key(&master, agent_pid).expect("derive_agent");
                assert_eq!(
                    agent_key.as_bytes().as_slice(),
                    expected_agent_key.as_slice(),
                    "{id}: derived agent key mismatch"
                );

                let mut plaintext = [0u8; 32];
                plaintext.copy_from_slice(&plaintext_vec);

                let mut nonce = [0u8; 12];
                nonce[..8].copy_from_slice(&iv_random);
                nonce[8..].copy_from_slice(&iv_counter.to_le_bytes());
                let aad = agent_pid.to_le_bytes();
                let (ct, tag) =
                    seal(agent_key.as_bytes(), &nonce, &aad, &plaintext).expect("seal");

                let mut wire = Vec::with_capacity(64);
                wire.extend_from_slice(&aad);
                wire.extend_from_slice(&iv_random);
                wire.extend_from_slice(&iv_counter.to_le_bytes());
                wire.extend_from_slice(&ct);
                wire.extend_from_slice(&tag);
                assert_eq!(wire, expected, "{id}: master-key wire mismatch");
                count += 1;
            }
            "kdf_agent_key" => {
                let master_bytes = decode_hex(&read_string(entry, "master_key_hex"));
                let agent_id = read_u32(entry, "agent_id");
                let expected = decode_hex(&read_string(entry, "expected_okm_hex"));
                let mut master_array = [0u8; 32];
                master_array.copy_from_slice(&master_bytes);
                let master = Key::from_bytes(master_array);
                let key = kdf::derive_agent_key(&master, agent_id).expect("derive");
                assert_eq!(key.as_bytes().as_slice(), expected.as_slice(), "{id}");
                count += 1;
            }
            "kdf_iv_prefix" => {
                let salt = decode_hex(&read_string(entry, "session_salt_hex"));
                let prefix_index = read_u32(entry, "prefix_index");
                let expected = decode_hex(&read_string(entry, "expected_iv_prefix_hex"));
                let mut salt_array = [0u8; 16];
                salt_array.copy_from_slice(&salt);
                let iv = kdf::derive_iv_prefix(&salt_array, prefix_index).expect("derive");
                assert_eq!(iv.as_slice(), expected.as_slice(), "{id}");
                count += 1;
            }
            "kdf_epoch_key" => {
                let agent_bytes = decode_hex(&read_string(entry, "agent_key_hex"));
                let epoch = read_u64(entry, "epoch");
                let expected = decode_hex(&read_string(entry, "expected_okm_hex"));
                let mut agent_array = [0u8; 32];
                agent_array.copy_from_slice(&agent_bytes);
                let agent_key = Key::from_bytes(agent_array);
                let derived = kdf::derive_epoch_key(&agent_key, epoch).expect("derive");
                assert_eq!(
                    derived.as_bytes().as_slice(),
                    expected.as_slice(),
                    "{id}"
                );
                count += 1;
            }
            other => panic!("{id}: unknown secure_frame kind: {other}"),
        }
    }
    assert!(count >= 5, "expected ≥5 secure-frame vectors, got {count}");
}
