#!/usr/bin/env python3
"""Generate a C header from the JSON conformance vectors.

The C reference covers the base VLP frame only — secure-transport AEAD
verification is left to the Python/Go/Rust references (writing a
ChaCha20-Poly1305 implementation in portable C99 is out of scope for a
reference snippet, and shipping libsodium linkage in this directory
trades portability for value the other references already deliver).

Usage:
    python3 gen_vectors_header.py /path/to/vlp-test-vectors.json > vectors.h
"""

import json
import sys
from pathlib import Path


STATUS_BY_NAME = {"ok": 0, "degraded": 1, "critical": 2}


def cstring(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def hex_to_c_array(hex_str: str, name: str) -> str:
    if not hex_str:
        return f"static const uint8_t {name}[1] = {{0}}; static const size_t {name}_len = 0;"
    body = ", ".join("0x" + hex_str[i:i + 2] for i in range(0, len(hex_str), 2))
    n = len(hex_str) // 2
    return f"static const uint8_t {name}[{n}] = {{{body}}}; static const size_t {name}_len = {n};"


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("usage: gen_vectors_header.py <vectors.json>", file=sys.stderr)
        return 1
    path = Path(argv[1])
    doc = json.loads(path.read_text())

    print("// AUTO-GENERATED by gen_vectors_header.py — DO NOT EDIT.")
    print("// Re-run after regenerating tools/vlp-test-vectors.json.")
    print("#ifndef VARTA_VECTORS_H")
    print("#define VARTA_VECTORS_H")
    print("#include <stddef.h>")
    print("#include <stdint.h>")
    print()

    print("typedef struct { const char *id; const uint8_t *input; size_t input_len;")
    print("                 uint32_t expected_crc; } crc_vec_t;")
    print()
    print("typedef struct { const char *id; const uint8_t *wire;")
    print("                 int status; uint32_t pid; uint64_t timestamp;")
    print("                 uint64_t nonce; uint32_t payload;")
    print("                 const char *expected_decode_error; } frame_vec_t;")
    print()

    # ----- CRC vectors -----
    for i, v in enumerate(doc["crc32c_vectors"]):
        print(hex_to_c_array(v["input_hex"], f"crc_in_{i}"))
    print()
    print("static const crc_vec_t crc_vectors[] = {")
    for i, v in enumerate(doc["crc32c_vectors"]):
        print(f"    {{{cstring(v['id'])}, crc_in_{i}, crc_in_{i}_len, 0x{v['expected_crc_hex']}u}},")
    print("};")
    print(f"static const size_t crc_vectors_count = {len(doc['crc32c_vectors'])};")
    print()

    # ----- Frame vectors -----
    for i, v in enumerate(doc["frame_vectors"]):
        hex_str = v.get("expected_wire_hex") or v.get("wire_hex") or ""
        print(hex_to_c_array(hex_str, f"frame_wire_{i}"))
    print()
    print("static const frame_vec_t frame_vectors[] = {")
    for i, v in enumerate(doc["frame_vectors"]):
        kind = v["kind"]
        if kind == "encode_decode_roundtrip":
            inp = v["inputs"]
            status = STATUS_BY_NAME[inp["status"]]
            print(f"    {{{cstring(v['id'])}, frame_wire_{i},")
            print(f"     {status}, {inp['pid']}u, {inp['timestamp']}uLL,")
            print(f"     {inp['nonce']}uLL, {inp['payload']}u, NULL}},")
        else:
            err = v.get("expected_decode_error") or ""
            print(f"    {{{cstring(v['id'])}, frame_wire_{i},")
            print(f"     -1, 0, 0, 0, 0, {cstring(err)}}},")
    print("};")
    print(f"static const size_t frame_vectors_count = {len(doc['frame_vectors'])};")
    print()
    print("#endif /* VARTA_VECTORS_H */")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
