{{- if not .Values.alertmanager.slack.existingSecret.name -}}
{{- if .Values.alertmanager.slack.webhookUrl -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "varta-watch.slackSecretName" . }}
  namespace: {{ include "varta-watch.namespace" . }}
  labels:
    {{- include "varta-watch.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "varta-watch.slackSecretKey" . }}: {{ .Values.alertmanager.slack.webhookUrl | quote }}
{{- end -}}
{{- end -}}
