{{- if not .Values.prometheusToken.existingSecret.name -}}
{{- if .Values.prometheusToken.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "varta-watch.tokenSecretName" . }}
  namespace: {{ include "varta-watch.namespace" . }}
  labels:
    {{- include "varta-watch.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "varta-watch.tokenSecretKey" . }}: {{ .Values.prometheusToken.token | quote }}
{{- end -}}
{{- end -}}
